-- MySQL Script generated by MySQL Workbench
-- ven. 28 avril 2017 16:31:57 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_question
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_question
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_question` DEFAULT CHARACTER SET utf8 ;
USE `db_question` ;

-- -----------------------------------------------------
-- Table `db_question`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`post` (
  `idPost` INT(11) NOT NULL AUTO_INCREMENT,
  `textePost` VARCHAR(45) NULL DEFAULT NULL,
  `titrePost` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idPost`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_question`.`competences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`competences` (
  `idCompetence` INT(11) NOT NULL AUTO_INCREMENT,
  `nomCompetence` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCompetence`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_question`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`users` (
  `idUser` INT(11) NOT NULL AUTO_INCREMENT,
  `pseudoUser` VARCHAR(45) NOT NULL,
  `emailUser` VARCHAR(255) NOT NULL,
  `passwordUser` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_question`.`favoris`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`favoris` (
  `idFavoris` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser` INT(11) NOT NULL,
  `idPost` INT(11) NOT NULL,
  PRIMARY KEY (`idFavoris`),
  INDEX `fk_favoris_user_idx` (`idUser` ASC),
  INDEX `fk_favoris_post_idx` (`idPost` ASC),
  CONSTRAINT `fk_favoris_post`
    FOREIGN KEY (`idPost`)
    REFERENCES `db_question`.`post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_favoris_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `db_question`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_question`.`niveau_competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`niveau_competence` (
  `idNiveau_competence` INT(11) NOT NULL AUTO_INCREMENT,
  `nomNiveau_competence` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idNiveau_competence`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_question`.`groupe_competence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`groupe_competence` (
  `idGroupe_competence` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser` INT(11) NOT NULL,
  `idCompetence` INT(11) NOT NULL,
  `idNiveau` INT(11) NOT NULL,
  PRIMARY KEY (`idGroupe_competence`),
  INDEX `idUser_idx` (`idUser` ASC),
  INDEX `idCompetence_idx` (`idCompetence` ASC),
  INDEX `idNiveau_idx` (`idNiveau` ASC),
  CONSTRAINT `idNiveau`
    FOREIGN KEY (`idNiveau`)
    REFERENCES `db_question`.`niveau_competence` (`idNiveau_competence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCompetence`
    FOREIGN KEY (`idCompetence`)
    REFERENCES `db_question`.`competences` (`idCompetence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `db_question`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_question`.`listeCompPost`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`listeCompPost` (
  `idListeCompPost` INT(11) NOT NULL AUTO_INCREMENT,
  `idCompetence` INT(11) NOT NULL,
  `idPost` INT(11) NOT NULL,
  PRIMARY KEY (`idListeCompPost`),
  INDEX `fk_listeCompPost_post_idx` (`idPost` ASC),
  INDEX `fk_listeCompPost_competence_idx` (`idCompetence` ASC),
  CONSTRAINT `fk_listeCompPost_competence`
    FOREIGN KEY (`idCompetence`)
    REFERENCES `db_question`.`competences` (`idCompetence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_listeCompPost_post`
    FOREIGN KEY (`idPost`)
    REFERENCES `db_question`.`post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_question`.`message`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`message` (
  `idMessage` INT(11) NOT NULL AUTO_INCREMENT,
  `idUser` INT(11) NOT NULL,
  `textMessage` VARCHAR(45) NOT NULL,
  `idPost` INT(11) NOT NULL,
  `isMainMessage` TINYINT(1) NOT NULL,
  `dateMessage` DATETIME NOT NULL,
  `scoreMessage` INT(11) NOT NULL,
  PRIMARY KEY (`idMessage`),
  INDEX `idUser_idx` (`idUser` ASC),
  INDEX `idPost_idx` (`idPost` ASC),
  CONSTRAINT `fk_message_post`
    FOREIGN KEY (`idPost`)
    REFERENCES `db_question`.`post` (`idPost`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_message_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `db_question`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_question`.`vote`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_question`.`vote` (
  `idVote` INT(11) NOT NULL AUTO_INCREMENT,
  `idMessage` INT(11) NOT NULL,
  `idUser` INT(11) NOT NULL,
  `boolVote` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idVote`),
  INDEX `fk_vote_Message_idx` (`idMessage` ASC),
  INDEX `fk_vote_user_idx` (`idUser` ASC),
  CONSTRAINT `fk_vote_message`
    FOREIGN KEY (`idMessage`)
    REFERENCES `db_question`.`message` (`idMessage`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_vote_user`
    FOREIGN KEY (`idUser`)
    REFERENCES `db_question`.`users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
